- name: Fetch kubeconfig from primary node
  hosts: aries1
  become: true
  tasks:
    - name: Read kubeconfig from aries1
      ansible.builtin.slurp:
        src: /etc/rancher/k3s/k3s.yaml
      register: kcfg

    - name: Write kubeconfig locally
      delegate_to: localhost
      become: false
      ansible.builtin.copy:
        dest: ./artifacts/kubeconfig
        content: "{{ kcfg.content | b64decode | regex_replace('127.0.0.1|localhost', hostvars[inventory_hostname].ansible_host) }}"
        mode: "0600"
