common_packages:
  - curl
  - jq
  - htop
  - vim
  - git
  - ntp
  - python3
  - python3-venv
  - python3-pip
  - apt-transport-https
  - ca-certificates
  - nfs-common
  - open-iscsi   # Longhorn requirement
  - multipath-tools
sysctl_tweaks:
  "vm.swappiness": "10"
  "fs.inotify.max_user_watches": "524288"
  "fs.inotify.max_user_instances": "1024"
  "net.ipv4.ip_forward": "1"
ansible_admin_user: ubuntu

# K3s configuration
k3s_version: "v1.28.3+k3s2"
k3s_primary_ip: "10.0.0.233"  # aries1's IP
cluster_cidr: "10.42.0.0/16"
service_cidr: "10.43.0.0/16"
k3s_exec_extra: "--disable traefik --disable servicelb"
